// Gemeinden in Sachsen
const SelektierbareOptionenAufzaehlungsWertGemeindenSN = [
    "Adorf/Vogtl., Stadt",
    "Altenberg, Stadt",
    "Altmittweida",
    "Amtsberg",
    "Annaberg-Buchholz, Stadt",
    "Arnsdorf",
    "Arzberg",
    "Aue, Stadt",
    "Auerbach",
    "Auerbach/Vogtl., Stadt",
    "Augustusburg, Stadt",
    "Bad Brambach",
    "Bad Düben, Stadt",
    "Bad Elster, Stadt",
    "Bad Gottleuba-Berggießhübel, Stadt",
    "Bad Lausick, Stadt",
    "Bad Muskau, Stadt",
    "Bad Schandau, Stadt",
    "Bad Schlema",
    "Bahretal",
    "Bannewitz",
    "Bärenstein",
    "Bautzen, Stadt",
    "Beiersdorf",
    "Beilrode",
    "Belgern-Schildau, Stadt",
    "Belgershain",
    "Bennewitz",
    "Bergen",
    "Bernsdorf",
    "Bernsdorf, Stadt",
    "Bernstadt a. d. Eigen, Stadt",
    "Bertsdorf-Hörnitz",
    "Bischofswerda, Stadt",
    "Bobritzsch-Hilbersdorf",
    "Bockau",
    "Böhlen, Stadt",
    "Borna, Stadt",
    "Börnichen/Erzgeb.",
    "Borsdorf",
    "Bösenbrunn",
    "Boxberg/O.L.",
    "Brand-Erbisdorf, Stadt",
    "Brandis, Stadt",
    "Breitenbrunn/Erzgeb.",
    "Bretnig-Hauswalde",
    "Burgstädt, Stadt",
    "Burkau",
    "Burkhardtsdorf",
    "Callenberg",
    "Cavertitz",
    "Chemnitz, Stadt",
    "Claußnitz",
    "Colditz, Stadt",
    "Coswig, Stadt",
    "Crimmitschau, Stadt",
    "Crinitzberg",
    "Crostwitz",
    "Crottendorf",
    "Cunewalde",
    "Dahlen, Stadt",
    "Delitzsch, Stadt",
    "Demitz-Thumitz",
    "Dennheritz",
    "Deutschneudorf",
    "Diera-Zehren",
    "Dippoldiswalde, Stadt",
    "Döbeln, Stadt",
    "Doberschau-Gaußig",
    "Doberschütz",
    "Dohma",
    "Dohna, Stadt",
    "Dommitzsch, Stadt",
    "Dorfchemnitz",
    "Dorfhain",
    "Drebach",
    "Dreiheide",
    "Dresden, Stadt",
    "Dürrhennersdorf",
    "Dürrröhrsdorf-Dittersbach",
    "Ebersbach",
    "Ebersbach-Neugersdorf, Stadt",
    "Ehrenfriedersdorf, Stadt",
    "Eibenstock, Stadt",
    "Eichigt",
    "Eilenburg, Stadt",
    "Ellefeld",
    "Elsnig",
    "Elsterberg, Stadt",
    "Elsterheide",
    "Elstertrebnitz",
    "Elstra, Stadt",
    "Elterlein, Stadt",
    "Eppendorf",
    "Erlau",
    "Falkenstein/Vogtl., Stadt",
    "Flöha, Stadt",
    "Frankenberg/Sa., Stadt",
    "Frankenthal",
    "Frauenstein, Stadt",
    "Fraureuth",
    "Freiberg, Stadt, Universitätsstadt",
    "Freital, Stadt",
    "Frohburg, Stadt",
    "Gablenz",
    "Geithain, Stadt",
    "Gelenau/Erzgeb.",
    "Geringswalde, Stadt",
    "Gersdorf",
    "Geyer, Stadt",
    "Glashütte, Stadt",
    "Glaubitz",
    "Glauchau, Stadt",
    "Göda",
    "Gohrisch",
    "Görlitz, Stadt",
    "Gornau/Erzgeb.",
    "Gornsdorf",
    "Grimma, Stadt",
    "Gröditz, Stadt",
    "Groitzsch, Stadt",
    "Groß Düben",
    "Großdubrau",
    "Großenhain, Stadt",
    "Großharthau",
    "Großhartmannsdorf",
    "Großnaundorf",
    "Großolbersdorf",
    "Großpösna",
    "Großpostwitz/O.L.",
    "Großröhrsdorf, Stadt",
    "Großrückerswalde",
    "Großschirma, Stadt",
    "Großschönau",
    "Großschweidnitz",
    "Großweitzschen",
    "Grünbach",
    "Grünhain-Beierfeld, Stadt",
    "Grünhainichen",
    "Hähnichen",
    "Hainewalde",
    "Hainichen, Stadt",
    "Halsbrücke",
    "Hartenstein, Stadt",
    "Hartha, Stadt",
    "Hartmannsdorf",
    "Hartmannsdorf b. Kirchberg",
    "Hartmannsdorf-Reichenau",
    "Haselbachtal",
    "Heidenau, Stadt",
    "Heidersdorf",
    "Heinsdorfergrund",
    "Hermsdorf/Erzgeb.",
    "Herrnhut, Stadt",
    "Hirschfeld",
    "Hirschstein",
    "Hochkirch",
    "Hohendubrau",
    "Hohenstein-Ernstthal, Stadt",
    "Hohndorf",
    "Hohnstein, Stadt",
    "Horka",
    "Hoyerswerda, Stadt",
    "Jahnsdorf/Erzgeb.",
    "Jesewitz",
    "Johanngeorgenstadt, Stadt",
    "Jöhstadt, Stadt",
    "Jonsdorf, Kurort",
    "Käbschütztal",
    "Kamenz, Stadt",
    "Kirchberg, Stadt",
    "Kitzscher, Stadt",
    "Klingenberg",
    "Klingenthal, Stadt",
    "Klipphausen",
    "Kodersdorf",
    "Kohren-Sahlis, Stadt",
    "Königsbrück, Stadt",
    "Königsfeld",
    "Königshain",
    "Königshain-Wiederau",
    "Königstein/Sächs. Schw., Stadt",
    "Königswalde",
    "Königswartha",
    "Kottmar",
    "Krauschwitz",
    "Kreba-Neudorf",
    "Kreischa",
    "Kriebstein",
    "Krostitz",
    "Kubschütz",
    "Lampertswalde",
    "Langenbernsdorf",
    "Langenweißbach",
    "Laußig",
    "Laußnitz",
    "Lauta, Stadt",
    "Lauter-Bernsbach, Stadt",
    "Lawalde",
    "Leipzig, Stadt",
    "Leisnig, Stadt",
    "Lengenfeld, Stadt",
    "Leubsdorf",
    "Leutersdorf",
    "Lichtenau",
    "Lichtenberg",
    "Lichtenberg/Erzgeb.",
    "Lichtenstein/Sa., Stadt",
    "Lichtentanne",
    "Liebschützberg",
    "Liebstadt, Stadt",
    "Limbach",
    "Limbach-Oberfrohna, Stadt",
    "Löbau, Stadt",
    "Löbnitz",
    "Lohmen",
    "Lohsa",
    "Lommatzsch, Stadt",
    "Lossatal",
    "Lößnitz, Stadt",
    "Lugau/Erzgeb., Stadt",
    "Lunzenau, Stadt",
    "Machern",
    "Malschwitz",
    "Marienberg, Stadt",
    "Markersdorf",
    "Markkleeberg, Stadt",
    "Markneukirchen, Stadt",
    "Markranstädt, Stadt",
    "Meerane, Stadt",
    "Meißen, Stadt",
    "Mildenau",
    "Mittelherwigsdorf",
    "Mittweida, Stadt, Hochschulstadt",
    "Mochau",
    "Mockrehna",
    "Moritzburg",
    "Mücka",
    "Mügeln, Stadt",
    "Müglitztal",
    "Mühlau",
    "Mühlental",
    "Mulda/Sa.",
    "Muldenhammer",
    "Mülsen",
    "Mylau, Stadt",
    "Narsdorf",
    "Naundorf",
    "Naunhof, Stadt",
    "Nebelschütz",
    "Neißeaue",
    "Neschwitz",
    "Netzschkau, Stadt",
    "Neuensalz",
    "Neuhausen/Erzgeb.",
    "Neukieritzsch",
    "Neukirch",
    "Neukirch/Lausitz",
    "Neukirchen/Erzgeb.",
    "Neukirchen/Pleiße",
    "Neumark",
    "Neusalza-Spremberg, Stadt",
    "Neustadt i. Sa., Stadt",
    "Neustadt/Vogtl.",
    "Niederau",
    "Niederdorf",
    "Niederfrohna",
    "Niederwiesa",
    "Niederwürschnitz",
    "Niesky, Stadt",
    "Nossen, Stadt",
    "Nünchritz",
    "Obergurig",
    "Oberlungwitz, Stadt",
    "Oberschöna",
    "Oberwiera",
    "Oberwiesenthal, Kurort, Stadt",
    "Oderwitz",
    "Oederan, Stadt",
    "Oelsnitz/Erzgeb., Stadt",
    "Oelsnitz/Vogtl., Stadt",
    "Ohorn",
    "Olbernhau, Stadt",
    "Olbersdorf",
    "Oppach",
    "Oschatz, Stadt",
    "Oßling",
    "Ostrau",
    "Ostritz, Stadt",
    "Ottendorf-Okrilla",
    "Otterwisch",
    "Oybin",
    "Panschwitz-Kuckau",
    "Parthenstein",
    "Pausa-Mühltroff, Stadt",
    "Pegau, Stadt",
    "Penig, Stadt",
    "Pfaffroda",
    "Pirna, Stadt",
    "Plauen, Stadt",
    "Pockau-Lengefeld, Stadt",
    "Pöhl",
    "Priestewitz",
    "Pulsnitz, Stadt",
    "Puschwitz",
    "Quitzdorf am See",
    "Rabenau, Stadt",
    "Räckelwitz",
    "Rackwitz",
    "Radeberg, Stadt",
    "Radebeul, Stadt",
    "Radeburg, Stadt",
    "Radibor",
    "Ralbitz-Rosenthal",
    "Rammenau",
    "Raschau-Markersbach",
    "Rathen, Kurort",
    "Rathmannsdorf",
    "Rechenberg-Bienenmühle",
    "Regis-Breitingen, Stadt",
    "Reichenbach im Vogtland, Stadt",
    "Reichenbach/O.L., Stadt",
    "Reinhardtsdorf-Schöna",
    "Reinsberg",
    "Reinsdorf",
    "Remse",
    "Reuth",
    "Riesa, Stadt",
    "Rietschen",
    "Rochlitz, Stadt",
    "Röderaue",
    "Rodewisch, Stadt",
    "Rosenbach",
    "Rosenbach/Vogtl.",
    "Rosenthal-Bielatal",
    "Rossau",
    "Roßwein, Stadt",
    "Rötha, Stadt",
    "Rothenburg/O.L., Stadt",
    "Sayda, Stadt",
    "Scheibenberg, Stadt",
    "Schirgiswalde-Kirschau, Stadt",
    "Schkeuditz, Stadt",
    "Schleife",
    "Schlettau, Stadt",
    "Schmölln-Putzkau",
    "Schneeberg, Stadt",
    "Schönau-Berzdorf a. d. Eigen",
    "Schönbach",
    "Schönberg",
    "Schöneck/Vogtl., Stadt",
    "Schönfeld",
    "Schönheide",
    "Schönteichen",
    "Schönwölkau",
    "Schöpstal",
    "Schwarzenberg/Erzgeb., Stadt",
    "Schwepnitz",
    "Sebnitz, Stadt",
    "Seelitz",
    "Sehmatal",
    "Seiffen/Erzgeb., Kurort",
    "Seifhennersdorf, Stadt",
    "Sohland a. d. Spree",
    "Spreetal",
    "St. Egidien",
    "Stadt Wehlen, Stadt",
    "Stauchitz",
    "Steina",
    "Steinberg",
    "Steinigtwolmsdorf",
    "Stollberg/Erzgeb., Stadt",
    "Stolpen, Stadt",
    "Strehla, Stadt",
    "Striegistal",
    "Struppen",
    "Stützengrün",
    "Tannenberg",
    "Taucha, Stadt",
    "Taura",
    "Tauscha",
    "Thalheim/Erzgeb., Stadt",
    "Thallwitz",
    "Tharandt, Stadt",
    "Thermalbad Wiesenbad",
    "Theuma",
    "Thiendorf",
    "Thum, Stadt",
    "Tirpersdorf",
    "Torgau, Stadt",
    "Trebendorf",
    "Trebsen/Mulde, Stadt",
    "Treuen, Stadt",
    "Triebel/Vogtl.",
    "Trossin",
    "Vierkirchen",
    "Wachau",
    "Waldenburg, Stadt",
    "Waldheim, Stadt",
    "Waldhufen",
    "Wechselburg",
    "Weinböhla",
    "Weischlitz",
    "Weißenberg, Stadt",
    "Weißenborn/Erzgeb.",
    "Weißkeißel",
    "Weißwasser/O.L., Stadt",
    "Werda",
    "Werdau, Stadt",
    "Wermsdorf",
    "Wiedemar",
    "Wildenfels, Stadt",
    "Wilkau-Haßlau, Stadt",
    "Wilsdruff, Stadt",
    "Wilthen, Stadt",
    "Wittichenau, Stadt",
    "Wolkenstein, Stadt",
    "Wülknitz",
    "Wurzen, Stadt",
    "Zeithain",
    "Zettlitz",
    "Zittau, Stadt",
    "Zschaitz-Ottewig",
    "Zschepplin",
    "Zschopau, Stadt",
    "Zschorlau",
    "Zwenkau, Stadt",
    "Zwickau, Stadt",
    "Zwönitz, Stadt",
];

module.exports = SelektierbareOptionenAufzaehlungsWertGemeindenSN;
