// Gemeinden in Hessen
const SelektierbareOptionenAufzaehlungsWertGemeindenHE = [
  "Aarbergen",
  "Abtsteinach",
  "Ahnatal",
  "Alheim",
  "Allendorf (Eder)",
  "Allendorf (Lumda), Stadt",
  "Alsbach-Hähnlein",
  "Alsfeld, Stadt",
  "Altenstadt",
  "Amöneburg, Stadt",
  "Angelburg",
  "Antrifttal",
  "Aßlar, Stadt",
  "Babenhausen, Stadt",
  "Bad Arolsen, Stadt",
  "Bad Camberg, Stadt",
  "Bad Emstal",
  "Bad Endbach",
  "Bad Hersfeld, Kreisstadt",
  "Bad Homburg v. d. Höhe, Stadt",
  "Bad Karlshafen, Stadt",
  "Bad König, Stadt",
  "Bad Nauheim, Stadt",
  "Bad Orb, Stadt",
  "Bad Salzschlirf",
  "Bad Schwalbach, Kreisstadt",
  "Bad Soden am Taunus, Stadt",
  "Bad Soden-Salmünster, Stadt",
  "Bad Sooden-Allendorf, Stadt",
  "Bad Vilbel, Stadt",
  "Bad Wildungen, Stadt",
  "Bad Zwesten",
  "Battenberg (Eder), Stadt",
  "Baunatal, Stadt",
  "Bebra, Stadt",
  "Beerfelden, Stadt",
  "Bensheim, Stadt",
  "Berkatal",
  "Beselich",
  "Biblis",
  "Bickenbach",
  "Biebergemünd",
  "Biebertal",
  "Biebesheim am Rhein",
  "Biedenkopf, Stadt",
  "Birkenau",
  "Birstein",
  "Bischoffen",
  "Bischofsheim",
  "Borken (Hessen), Stadt",
  "Brachttal",
  "Braunfels, Stadt",
  "Brechen",
  "Breidenbach",
  "Breitenbach a. Herzberg",
  "Breitscheid",
  "Brensbach",
  "Breuberg, Stadt",
  "Breuna",
  "Brombachtal",
  "Bromskirchen",
  "Bruchköbel, Stadt",
  "Büdingen, Stadt",
  "Burghaun, Marktgemeinde",
  "Burgwald",
  "Bürstadt, Stadt",
  "Buseck",
  "Büttelborn",
  "Butzbach, Friedrich-Ludwig-Weidig-Stadt",
  "Calden",
  "Cölbe",
  "Cornberg",
  "Darmstadt, Wissenschaftsstadt",
  "Dautphetal",
  "Dieburg, Stadt",
  "Diemelsee",
  "Diemelstadt, Stadt",
  "Dietzenbach, Kreisstadt",
  "Dietzhölztal",
  "Dillenburg, Stadt",
  "Dipperz",
  "Dornburg",
  "Dreieich, Stadt",
  "Driedorf",
  "Ebersburg",
  "Ebsdorfergrund",
  "Echzell",
  "Edermünde",
  "Edertal",
  "Egelsbach",
  "Ehrenberg (Rhön)",
  "Ehringshausen",
  "Eichenzell",
  "Einhausen",
  "Eiterfeld, Marktgemeinde",
  "Elbtal",
  "Eltville am Rhein, Stadt",
  "Elz",
  "Eppertshausen",
  "Eppstein, Stadt",
  "Erbach, Kreisstadt",
  "Erlensee, Stadt",
  "Erzhausen",
  "Eschborn, Stadt",
  "Eschenburg",
  "Eschwege, Kreisstadt",
  "Espenau",
  "Feldatal",
  "Felsberg, Stadt",
  "Fernwald",
  "Fischbachtal",
  "Flieden",
  "Flörsbachtal",
  "Flörsheim am Main, Stadt",
  "Florstadt, Stadt",
  "Frankenau, Stadt",
  "Frankenberg (Eder), Stadt",
  "Frankfurt am Main, Stadt",
  "Fränkisch-Crumbach",
  "Freiensteinau",
  "Freigericht",
  "Friedberg (Hessen), Kreisstadt",
  "Friedewald",
  "Friedrichsdorf, Stadt",
  "Frielendorf",
  "Fritzlar, Dom- und Kaiserstadt",
  "Fronhausen",
  "Fulda, Stadt",
  "Fuldabrück",
  "Fuldatal",
  "Fürth",
  "Gedern, Stadt",
  "Geisenheim, Hochschulstadt",
  "Gelnhausen, Barbarossast., Krst.",
  "Gemünden (Felda)",
  "Gemünden (Wohra), Stadt",
  "Gernsheim, Schöfferstadt",
  "Gersfeld (Rhön), Stadt",
  "Gießen, Universitätsstadt",
  "Gilserberg",
  "Ginsheim-Gustavsburg, Stadt",
  "Gladenbach, Stadt",
  "Glashütten",
  "Glauburg",
  "Gorxheimertal",
  "Grasellenbach",
  "Grävenwiesbach",
  "Grebenau, Stadt",
  "Grebenhain",
  "Grebenstein, Stadt",
  "Greifenstein",
  "Griesheim, Stadt",
  "Großalmerode, Stadt",
  "Groß-Bieberau, Stadt",
  "Großenlüder",
  "Groß-Gerau, Stadt",
  "Großkrotzenburg",
  "Groß-Rohrheim",
  "Groß-Umstadt, Stadt",
  "Groß-Zimmern",
  "Grünberg, Stadt",
  "Gründau",
  "Gudensberg, Stadt",
  "Gutsbezirk Kaufunger Wald, gemfr. Gebiet",
  "Gutsbezirk Reinhardswald, gemfr. Gebiet",
  "Gutsbezirk Spessart, gemfr. Gebiet",
  "Guxhagen",
  "Habichtswald",
  "Hadamar, Stadt",
  "Haiger, Stadt",
  "Haina (Kloster)",
  "Hainburg",
  "Hammersbach",
  "Hanau, Brüder-Grimm-Stadt",
  "Hasselroth",
  "Hattersheim am Main, Stadt",
  "Hatzfeld (Eder), Stadt",
  "Hauneck",
  "Haunetal",
  "Heidenrod",
  "Helsa",
  "Heppenheim (Bergstraße), Kreisstadt",
  "Herborn, Stadt",
  "Herbstein, Stadt",
  "Heringen (Werra), Stadt",
  "Herleshausen",
  "Hesseneck",
  "Hessisch Lichtenau, Stadt",
  "Heuchelheim",
  "Heusenstamm, Stadt",
  "Hilders",
  "Hirschhorn (Neckar), Stadt",
  "Hirzenhain",
  "Hochheim am Main, Stadt",
  "Höchst i. Odw.",
  "Hofbieber",
  "Hofgeismar, Stadt",
  "Hofheim am Taunus, Kreisstadt",
  "Hohenahr",
  "Hohenroda",
  "Hohenstein",
  "Homberg (Efze), Reformationsstadt, Kreisstadt",
  "Homberg (Ohm), Stadt",
  "Hosenfeld",
  "Hünfeld, Konrad-Zuse-Stadt",
  "Hünfelden",
  "Hungen, Stadt",
  "Hünstetten",
  "Hüttenberg",
  "Idstein, Stadt",
  "Immenhausen, Stadt",
  "Jesberg",
  "Jossgrund",
  "Kalbach",
  "Karben, Stadt",
  "Kassel, documenta-Stadt",
  "Kaufungen",
  "Kefenrod",
  "Kelkheim (Taunus), Stadt",
  "Kelsterbach, Stadt",
  "Kiedrich",
  "Kirchhain, Stadt",
  "Kirchheim",
  "Kirtorf, Stadt",
  "Knüllwald",
  "Königstein im Taunus, Stadt",
  "Korbach, Hansestadt",
  "Körle",
  "Kriftel",
  "Kronberg im Taunus, Stadt",
  "Künzell",
  "Lahnau",
  "Lahntal",
  "Lampertheim, Stadt",
  "Langen (Hessen), Stadt",
  "Langenselbold, Stadt",
  "Langgöns",
  "Laubach, Stadt",
  "Lauterbach (Hessen), Kreisstadt",
  "Lautertal (Odenwald)",
  "Lautertal (Vogelsberg)",
  "Leun, Stadt",
  "Lich, Stadt",
  "Lichtenfels, Stadt",
  "Liebenau, Stadt",
  "Liederbach am Taunus",
  "Limburg a.d. Lahn, Kreisstadt",
  "Limeshain",
  "Linden, Stadt",
  "Lindenfels, Stadt",
  "Linsengericht",
  "Lohfelden",
  "Löhnberg",
  "Lohra",
  "Lollar, Stadt",
  "Lorch, Stadt",
  "Lorsch, Karolingerstadt",
  "Ludwigsau",
  "Lützelbach",
  "Mainhausen",
  "Maintal, Stadt",
  "Malsfeld",
  "Marburg, Universitätsstadt",
  "Meinhard",
  "Meißner",
  "Melsungen, Stadt",
  "Mengerskirchen, Marktflecken",
  "Merenberg, Marktflecken",
  "Messel",
  "Michelbuch, gemfr. Gebiet",
  "Michelstadt, Stadt",
  "Mittenaar",
  "Modautal",
  "Mörfelden-Walldorf, Stadt",
  "Mörlenbach",
  "Morschen",
  "Mossautal",
  "Mücke",
  "Mühlheim am Main, Stadt",
  "Mühltal",
  "Münchhausen",
  "Münster",
  "Münzenberg, Stadt",
  "Nauheim",
  "Naumburg, Stadt",
  "Neckarsteinach, Stadt",
  "Nentershausen",
  "Neu-Anspach, Stadt",
  "Neuberg",
  "Neu-Eichenberg",
  "Neuenstein",
  "Neuental",
  "Neuhof",
  "Neu-Isenburg, Stadt",
  "Neukirchen, Stadt",
  "Neustadt (Hessen), Stadt",
  "Nidda, Stadt",
  "Niddatal, Stadt",
  "Nidderau, Stadt",
  "Niedenstein, Stadt",
  "Niederaula, Marktgemeinde",
  "Niederdorfelden",
  "Niedernhausen",
  "Nieste",
  "Niestetal",
  "Nüsttal",
  "Oberaula",
  "Ober-Mörlen",
  "Ober-Ramstadt, Stadt",
  "Obertshausen, Stadt",
  "Oberursel (Taunus), Stadt",
  "Oberweser",
  "Oestrich-Winkel, Stadt",
  "Offenbach am Main, Stadt",
  "Ortenberg, Stadt",
  "Ottrau",
  "Otzberg",
  "Petersberg",
  "Pfungstadt, Stadt",
  "Philippsthal (Werra), Marktgemeinde",
  "Pohlheim, Stadt",
  "Poppenhausen (Wasserkuppe)",
  "Rabenau",
  "Ranstadt",
  "Rasdorf, Point-Alpha-Gemeinde",
  "Raunheim, Stadt",
  "Rauschenberg, Stadt",
  "Reichelsheim (Odenwald)",
  "Reichelsheim (Wetterau), Stadt",
  "Reinhardshagen",
  "Reinheim, Stadt",
  "Reiskirchen",
  "Riedstadt, Stadt",
  "Rimbach",
  "Ringgau",
  "Rockenberg",
  "Rodenbach",
  "Rödermark, Stadt",
  "Rodgau, Stadt",
  "Romrod, Stadt",
  "Ronneburg",
  "Ronshausen",
  "Rosbach v. d. Höhe, Stadt",
  "Rosenthal, Stadt",
  "Roßdorf",
  "Rotenburg a. d. Fulda, Stadt",
  "Rothenberg",
  "Rüdesheim am Rhein, Stadt",
  "Runkel, Stadt",
  "Rüsselsheim am Main, Stadt",
  "Schaafheim",
  "Schauenburg",
  "Schenklengsfeld",
  "Schlangenbad",
  "Schlitz, Stadt",
  "Schlüchtern, Stadt",
  "Schmitten",
  "Schöffengrund",
  "Schöneck",
  "Schotten, Stadt",
  "Schrecksbach",
  "Schwalbach am Taunus, Stadt",
  "Schwalmstadt, Stadt",
  "Schwalmtal",
  "Schwarzenborn, Stadt",
  "Seeheim-Jugenheim",
  "Seligenstadt, Stadt",
  "Selters (Taunus)",
  "Sensbachtal",
  "Siegbach",
  "Sinn",
  "Sinntal",
  "Söhrewald",
  "Solms, Stadt",
  "Sontra, Stadt",
  "Spangenberg, Liebenbachstadt",
  "Stadtallendorf, Stadt",
  "Staufenberg, Stadt",
  "Steffenberg",
  "Steinau an der Straße, Brüder-Grimm-Stadt",
  "Steinbach (Taunus), Stadt",
  "Stockstadt am Rhein",
  "Sulzbach (Taunus)",
  "Tann (Rhön), Stadt",
  "Taunusstein, Stadt",
  "Trebur",
  "Trendelburg, Stadt",
  "Twistetal",
  "Ulrichstein, Stadt",
  "Usingen, Stadt",
  "Vellmar, Stadt",
  "Viernheim, Stadt",
  "Villmar, Marktflecken",
  "Vöhl",
  "Volkmarsen, Stadt",
  "Wabern",
  "Wächtersbach, Stadt",
  "Wahlsburg",
  "Waldbrunn (Westerwald)",
  "Waldeck, Stadt",
  "Waldems",
  "Waldkappel, Stadt",
  "Wald-Michelbach",
  "Waldsolms",
  "Walluf",
  "Wanfried, Stadt",
  "Wartenberg",
  "Wehretal",
  "Wehrheim",
  "Weilburg, Stadt",
  "Weilmünster, Marktflecken",
  "Weilrod",
  "Weimar (Lahn)",
  "Weinbach",
  "Weißenborn",
  "Weiterstadt, Stadt",
  "Wettenberg",
  "Wetter (Hessen), Stadt",
  "Wetzlar, Stadt",
  "Wiesbaden, Landeshauptstadt",
  "Wildeck",
  "Willingen (Upland)",
  "Willingshausen",
  "Witzenhausen, Stadt",
  "Wohratal",
  "Wölfersheim",
  "Wolfhagen, Stadt",
  "Wöllstadt",
  "Zierenberg, Stadt",
  "Zwingenberg, Stadt"
];

module.exports = SelektierbareOptionenAufzaehlungsWertGemeindenHE;
