// Gemeinden in Bayern
const SelektierbareOptionenAufzaehlungsWertGemeindenBY = [
  "Abenberg, Stadt",
  "Abensberg, Stadt",
  "Absberg, Markt",
  "Abtswind, Markt",
  "Achslach",
  "Adelschlag",
  "Adelsdorf",
  "Adelshofen",
  "Adelshofen",
  "Adelsried",
  "Adelzhausen",
  "Adlkofen",
  "Affing",
  "Aham",
  "Aholfing",
  "Aholming",
  "Ahorn",
  "Ahorntal",
  "Aicha vorm Wald",
  "Aichach, Stadt",
  "Aichen",
  "Aidenbach, Markt",
  "Aidhausen",
  "Aiglsbach",
  "Aindling, Markt",
  "Ainring",
  "Aislingen, Markt",
  "Aiterhofen",
  "Aitrang",
  "Albaching",
  "Albertshofen",
  "Aldersbach",
  "Alerheim",
  "Alesheim",
  "Aletshausen",
  "Alfeld",
  "Allersberg, Markt",
  "Allershausen",
  "Alling",
  "Allmannshofen",
  "Altdorf b.Nürnberg, Stadt",
  "Altdorf, Markt",
  "Alteglofsheim",
  "Altenbuch",
  "Altendorf",
  "Altendorf",
  "Altenkunstadt",
  "Altenmarkt a.d.Alz",
  "Altenmünster",
  "Altenstadt",
  "Altenstadt a.d.Waldnaab",
  "Altenstadt, Markt",
  "Altenthann",
  "Altertheim",
  "Altfraunhofen",
  "Althegnenberg",
  "Altmannstein, Markt",
  "Altomünster, Markt",
  "Altötting, Stadt",
  "Altusried, Markt",
  "Alzenau, Stadt",
  "Amberg",
  "Amberg",
  "Amerang",
  "Amerdingen",
  "Ammerndorf, Markt",
  "Ammerthal",
  "Amorbach, Stadt",
  "Ampfing",
  "Andechs",
  "Anger",
  "Ansbach",
  "Antdorf",
  "Anzing",
  "Apfeldorf",
  "Apfeltrach",
  "Arberg, Markt",
  "Aresing",
  "Arnbruck",
  "Arnschwang",
  "Arnstein, Stadt",
  "Arnstorf, Markt",
  "Arrach",
  "Arzberg, Stadt",
  "Asbach-Bäumenheim",
  "Ascha",
  "Aschaffenburg",
  "Aschau a.Inn",
  "Aschau i.Chiemgau",
  "Aschheim",
  "Aßling",
  "Attenhofen",
  "Attenkirchen",
  "Atting",
  "Au i.d.Hallertau, Markt",
  "Aub, Stadt",
  "Aubstadt",
  "Auerbach",
  "Auerbach i.d.OPf., Stadt",
  "Aufhausen",
  "Aufseß",
  "Augsburg",
  "Auhausen",
  "Aura a.d.Saale",
  "Aura i.Sinngrund",
  "Aurach",
  "Aurachtal",
  "Außernzell",
  "Aying",
  "Aystetten",
  "Baar (Schwaben)",
  "Baar-Ebenhausen",
  "Babenhausen, Markt",
  "Babensham",
  "Bach a.d.Donau",
  "Bachhagel",
  "Bächingen a.d.Brenz",
  "Bad Abbach, Markt",
  "Bad Aibling, Stadt",
  "Bad Alexandersbad",
  "Bad Bayersoien",
  "Bad Berneck i.Fichtelgebirge, Stadt",
  "Bad Birnbach, Markt",
  "Bad Bocklet, Markt",
  "Bad Brückenau, Stadt",
  "Bad Endorf, Markt",
  "Bad Feilnbach",
  "Bad Füssing",
  "Bad Griesbach i.Rottal, Stadt",
  "Bad Grönenbach, Markt",
  "Bad Heilbrunn",
  "Bad Hindelang, Markt",
  "Bad Kissingen, Große Kreisstadt",
  "Bad Kohlgrub",
  "Bad Königshofen i.Grabfeld, Stadt",
  "Bad Kötzting, Stadt",
  "Bad Neustadt a.d.Saale, Stadt",
  "Bad Reichenhall, Große Kreisstadt",
  "Bad Rodach, Stadt",
  "Bad Staffelstein, Stadt",
  "Bad Steben, Markt",
  "Bad Tölz, Stadt",
  "Bad Wiessee",
  "Bad Windsheim, Stadt",
  "Bad Wörishofen, Stadt",
  "Baierbach",
  "Baierbrunn",
  "Baiern",
  "Baiersdorf, Stadt",
  "Baisweil",
  "Balderschwang",
  "Balzhausen",
  "Bamberg",
  "Barbing",
  "Bärnau, Stadt",
  "Bastheim",
  "Baudenbach, Markt",
  "Baunach, Stadt",
  "Bayerbach",
  "Bayerbach b.Ergoldsbach",
  "Bayerisch Eisenstein",
  "Bayerisch Gmain",
  "Bayreuth",
  "Bayrischzell",
  "Bechhofen, Markt",
  "Bechtsrieth",
  "Beilngries, Stadt",
  "Bellenberg",
  "Benediktbeuern",
  "Benningen",
  "Beratzhausen, Markt",
  "Berching, Stadt",
  "Berchtesgaden, Markt",
  "Berg",
  "Berg",
  "Berg b.Neumarkt i.d.OPf.",
  "Berg im Gau",
  "Bergen",
  "Bergen",
  "Bergheim",
  "Bergkirchen",
  "Berglern",
  "Bergrheinfeld",
  "Bergtheim",
  "Bernau a.Chiemsee",
  "Bernbeuren",
  "Berngau",
  "Bernhardswald",
  "Bernried",
  "Bernried am Starnberger See",
  "Bessenbach",
  "Betzenstein, Stadt",
  "Betzigau",
  "Beutelsbach",
  "Biberbach, Markt",
  "Bibertal",
  "Biburg",
  "Bichl",
  "Bidingen",
  "Biebelried",
  "Bieberehren",
  "Biessenhofen",
  "Bindlach",
  "Binswangen",
  "Birgland",
  "Birkenfeld",
  "Bischberg",
  "Bischbrunn",
  "Bischofsgrün",
  "Bischofsheim a.d.Rhön, Stadt",
  "Bischofsmais",
  "Bischofswiesen",
  "Bissingen, Markt",
  "Blaibach",
  "Blaichach",
  "Blankenbach",
  "Blindheim",
  "Böbing",
  "Bobingen, Stadt",
  "Böbrach",
  "Bockhorn",
  "Bodenkirchen",
  "Bodenmais, Markt",
  "Bodenwöhr",
  "Bodolz",
  "Bogen, Stadt",
  "Böhen",
  "Böhmfeld",
  "Bolsterlang",
  "Bonstetten",
  "Boos",
  "Brand",
  "Brannenburg",
  "Breitbrunn",
  "Breitbrunn a.Chiemsee",
  "Breitenberg",
  "Breitenbrunn",
  "Breitenbrunn, Markt",
  "Breitengüßbach",
  "Breitenthal",
  "Brennberg",
  "Bruck",
  "Bruck i.d.OPf., Markt",
  "Bruckberg",
  "Bruckberg",
  "Bruckmühl, Markt",
  "Brunn",
  "Brunnen",
  "Brunnthal",
  "Bubenreuth",
  "Bubesheim",
  "Buch a.Buchrain",
  "Buch a.Erlbach",
  "Buch a.Wald",
  "Buch, Markt",
  "Buchbach, Markt",
  "Buchbrunn",
  "Buchdorf",
  "Büchenbach",
  "Buchenberg, Markt",
  "Buchhofen",
  "Büchlberg",
  "Buchloe, Stadt",
  "Buckenhof",
  "Bundorf",
  "Burgau, Stadt",
  "Burgberg i.Allgäu",
  "Burgbernheim, Stadt",
  "Burgebrach, Markt",
  "Burggen",
  "Burghaslach, Markt",
  "Burghausen, Stadt",
  "Burgheim, Markt",
  "Burgkirchen a.d.Alz",
  "Burgkunstadt, Stadt",
  "Burglauer",
  "Burglengenfeld, Stadt",
  "Burgoberbach",
  "Burgpreppach, Markt",
  "Burgsalach",
  "Burgsinn, Markt",
  "Bürgstadt, Markt",
  "Burgthann",
  "Burgwindheim, Markt",
  "Burk",
  "Burkardroth, Markt",
  "Burtenbach, Markt",
  "Buttenheim, Markt",
  "Buttenwiesen",
  "Bütthard, Markt",
  "Buxheim",
  "Buxheim",
  "Cadolzburg, Markt",
  "Castell",
  "Cham, Stadt",
  "Chamerau",
  "Chieming",
  "Chiemsee",
  "Coburg",
  "Collenberg",
  "Colmberg, Markt",
  "Creußen, Stadt",
  "Dachau, Große Kreisstadt",
  "Dachsbach, Markt",
  "Daiting",
  "Dammbach",
  "Dasing",
  "Deggendorf, Große Kreisstadt",
  "Deining",
  "Deiningen",
  "Deisenhausen",
  "Denkendorf",
  "Denklingen",
  "Dentlein a.Forst, Markt",
  "Dettelbach, Stadt",
  "Deuerling",
  "Diebach",
  "Diedorf, Markt",
  "Diespeck",
  "Dießen am Ammersee, Markt",
  "Dietenhofen, Markt",
  "Dietersburg",
  "Dietersheim",
  "Dieterskirchen",
  "Dietfurt a.d.Altmühl, Stadt",
  "Dietmannsried, Markt",
  "Dietramszell",
  "Dillingen a.d.Donau, Große Kreisstadt",
  "Dingolfing, Stadt",
  "Dingolshausen",
  "Dinkelsbühl, Große Kreisstadt",
  "Dinkelscherben, Markt",
  "Dirlewang, Markt",
  "Dittelbrunn",
  "Dittenheim",
  "Döhlau",
  "Dollnstein, Markt",
  "Dombühl, Markt",
  "Donaustauf, Markt",
  "Donauwörth, Große Kreisstadt",
  "Donnersdorf",
  "Dorfen, Stadt",
  "Dörfles-Esbach",
  "Dorfprozelten",
  "Dormitz",
  "Drachselsried",
  "Duggendorf",
  "Durach",
  "Dürrlauingen",
  "Dürrwangen, Markt",
  "Ebelsbach",
  "Ebensfeld, Markt",
  "Eberfing",
  "Ebermannsdorf",
  "Ebermannstadt, Stadt",
  "Ebern, Stadt",
  "Ebersberg, Stadt",
  "Ebersdorf b.Coburg",
  "Ebershausen",
  "Ebnath",
  "Ebrach, Markt",
  "Eching",
  "Eching",
  "Eching am Ammersee",
  "Eckental, Markt",
  "Eckersdorf",
  "Edelsfeld",
  "Ederheim",
  "Edling",
  "Effeltrich",
  "Egenhofen",
  "Egg a.d.Günz",
  "Eggenfelden, Stadt",
  "Eggenthal",
  "Egglham",
  "Egglkofen",
  "Eggolsheim, Markt",
  "Eggstätt",
  "Eging a.See, Markt",
  "Eglfing",
  "Egling",
  "Egling a.d.Paar",
  "Egloffstein, Markt",
  "Egmating",
  "Egweil",
  "Ehekirchen",
  "Ehingen",
  "Ehingen",
  "Ehingen a.Ries",
  "Eibelstadt, Stadt",
  "Eichenau",
  "Eichenbühl",
  "Eichendorf, Markt",
  "Eichstätt, Große Kreisstadt",
  "Eiselfing",
  "Eisenberg",
  "Eisenheim, Markt",
  "Eisingen",
  "Eitensheim",
  "Eitting",
  "Elchingen",
  "Elfershausen, Markt",
  "Ellgau",
  "Ellingen, Stadt",
  "Ellzee",
  "Elsendorf",
  "Elsenfeld, Markt",
  "Eltmann, Stadt",
  "Emersacker",
  "Emmering",
  "Emmering",
  "Emmerting",
  "Emskirchen, Markt",
  "Emtmannsberg",
  "Engelsberg",
  "Engelthal",
  "Ensdorf",
  "Eppenschlag",
  "Eppishausen",
  "Erbendorf, Stadt",
  "Erding, Große Kreisstadt",
  "Erdweg",
  "Eresing",
  "Ergersheim",
  "Ergolding, Markt",
  "Ergoldsbach, Markt",
  "Erharting",
  "Ering",
  "Erkheim, Markt",
  "Erlabrunn",
  "Erlangen",
  "Erlbach",
  "Erlenbach a.Main, Stadt",
  "Erlenbach b.Marktheidenfeld",
  "Ermershausen",
  "Ernsgaden",
  "Eschau, Markt",
  "Eschenbach i.d.OPf., Stadt",
  "Eschenlohe",
  "Eschlkam, Markt",
  "Eslarn, Markt",
  "Esselbach",
  "Essenbach, Markt",
  "Essing, Markt",
  "Estenfeld",
  "Ettal",
  "Ettenstatt",
  "Ettringen",
  "Etzelwang",
  "Etzenricht",
  "Euerbach",
  "Euerdorf, Markt",
  "Eurasburg",
  "Eurasburg",
  "Eußenheim",
  "Fahrenzhausen",
  "Falkenberg",
  "Falkenberg, Markt",
  "Falkenfels",
  "Falkenstein, Markt",
  "Farchant",
  "Faulbach",
  "Feichten a.d.Alz",
  "Feilitzsch",
  "Feldafing",
  "Feldkirchen",
  "Feldkirchen",
  "Feldkirchen-Westerham",
  "Fellen",
  "Fellheim",
  "Fensterbach",
  "Feucht, Markt",
  "Feuchtwangen, Stadt",
  "Fichtelberg",
  "Finning",
  "Finningen",
  "Finsing",
  "Fischach, Markt",
  "Fischbachau",
  "Fischen i.Allgäu",
  "Flachslanden, Markt",
  "Fladungen, Stadt",
  "Flintsbach a.Inn",
  "Floß, Markt",
  "Flossenbürg",
  "Forchheim, Große Kreisstadt",
  "Forheim",
  "Forstern",
  "Forstinning",
  "Frammersbach, Markt",
  "Frankenwinheim",
  "Frasdorf",
  "Frauenau",
  "Frauenneuharting",
  "Fraunberg",
  "Freihung, Markt",
  "Freilassing, Stadt",
  "Freising, Große Kreisstadt",
  "Fremdingen",
  "Frensdorf",
  "Freudenberg",
  "Freystadt, Stadt",
  "Freyung, Stadt",
  "Frickenhausen a.Main, Markt",
  "Fridolfing",
  "Friedberg, Stadt",
  "Friedenfels",
  "Friesenried",
  "Frontenhausen, Markt",
  "Fuchsmühl, Markt",
  "Fuchsstadt",
  "Fuchstal",
  "Fünfstetten",
  "Fürsteneck",
  "Fürstenfeldbruck, Große Kreisstadt",
  "Fürstenstein",
  "Fürstenzell, Markt",
  "Furth",
  "Fürth",
  "Furth im Wald, Stadt",
  "Füssen, Stadt",
  "Gablingen",
  "Gachenbach",
  "Gädheim",
  "Gaimersheim, Markt",
  "Gaißach",
  "Gallmersgarten",
  "Gammelsdorf",
  "Gangkofen, Markt",
  "Garching a.d.Alz",
  "Garching b.München, Stadt",
  "Garmisch-Partenkirchen, Markt",
  "Gars a.Inn, Markt",
  "Gattendorf",
  "Gaukönigshofen",
  "Gauting",
  "Gdefr. Geb. (Lkr Amberg-Sulzbach)",
  "Gdefr. Geb. (Lkr Ansbach)",
  "Gdefr. Geb. (Lkr Aschaffenburg)",
  "Gdefr. Geb. (Lkr Augsburg)",
  "Gdefr. Geb. (Lkr Bad Kissingen)",
  "Gdefr. Geb. (Lkr Bad Tölz-Wolfratshausen)",
  "Gdefr. Geb. (Lkr Bamberg)",
  "Gdefr. Geb. (Lkr Bayreuth)",
  "Gdefr. Geb. (Lkr Berchtesgadener Land)",
  "Gdefr. Geb. (Lkr Coburg)",
  "Gdefr. Geb. (Lkr Donau-Ries)",
  "Gdefr. Geb. (Lkr Ebersberg)",
  "Gdefr. Geb. (Lkr Eichstätt)",
  "Gdefr. Geb. (Lkr Erlangen-Höchstadt)",
  "Gdefr. Geb. (Lkr Freyung-Grafenau)",
  "Gdefr. Geb. (Lkr Garmisch-Partenkirchen)",
  "Gdefr. Geb. (Lkr Günzburg)",
  "Gdefr. Geb. (Lkr Hof)",
  "Gdefr. Geb. (Lkr Kelheim)",
  "Gdefr. Geb. (Lkr Kronach)",
  "Gdefr. Geb. (Lkr Landsberg am Lech)",
  "Gdefr. Geb. (Lkr Lichtenfels)",
  "Gdefr. Geb. (Lkr Main-Spessart)",
  "Gdefr. Geb. (Lkr Miltenberg)",
  "Gdefr. Geb. (Lkr Mühldorf a.Inn)",
  "Gdefr. Geb. (Lkr München)",
  "Gdefr. Geb. (Lkr Neustadt a.d.Aisch-Bad Windsheim)",
  "Gdefr. Geb. (Lkr Neustadt a.d.Waldnaab)",
  "Gdefr. Geb. (Lkr Neu-Ulm)",
  "Gdefr. Geb. (Lkr Nürnberger Land)",
  "Gdefr. Geb. (Lkr Oberallgäu)",
  "Gdefr. Geb. (Lkr Regensburg)",
  "Gdefr. Geb. (Lkr Rhön-Grabfeld)",
  "Gdefr. Geb. (Lkr Rosenheim)",
  "Gdefr. Geb. (Lkr Roth)",
  "Gdefr. Geb. (Lkr Schwandorf)",
  "Gdefr. Geb. (Lkr Schweinfurt)",
  "Gdefr. Geb. (Lkr Starnberg)",
  "Gdefr. Geb. (Lkr Tirschenreuth)",
  "Gdefr. Geb. (Lkr Traunstein)",
  "Gdefr. Geb. (Lkr Unterallgäu)",
  "Gdefr. Geb. (Lkr Wunsiedel i.Fichtelgebirge)",
  "Gdefr. Geb. (Lkr Würzburg)",
  "Gebenbach",
  "Gebsattel",
  "Gefrees, Stadt",
  "Geiersthal",
  "Geiselbach",
  "Geiselhöring, Stadt",
  "Geiselwind, Markt",
  "Geisenfeld, Stadt",
  "Geisenhausen, Markt",
  "Gelchsheim, Markt",
  "Geldersheim",
  "Geltendorf",
  "Gemünden a.Main, Stadt",
  "Genderkingen",
  "Georgenberg",
  "Georgensgmünd",
  "Gerach",
  "Geratskirchen",
  "Gerbrunn",
  "Geretsried, Stadt",
  "Gerhardshofen",
  "Germaringen",
  "Germering, Große Kreisstadt",
  "Geroda, Markt",
  "Geroldsgrün",
  "Geroldshausen",
  "Gerolfingen",
  "Gerolsbach",
  "Gerolzhofen, Stadt",
  "Gersthofen, Stadt",
  "Gerzen",
  "Gesees",
  "Geslau",
  "Gessertshausen",
  "Gestratz",
  "Giebelstadt, Markt",
  "Gilching",
  "Glashütten",
  "Glattbach",
  "Gleiritsch",
  "Gleißenberg",
  "Glonn, Markt",
  "Glött",
  "Gmund a.Tegernsee",
  "Gnotzheim, Markt",
  "Gochsheim",
  "Goldbach, Markt",
  "Goldkronach, Stadt",
  "Gollhofen",
  "Görisried",
  "Gössenheim",
  "Gößweinstein, Markt",
  "Gotteszell",
  "Gottfrieding",
  "Graben",
  "Grabenstätt",
  "Gräfelfing",
  "Grafenau, Stadt",
  "Gräfenberg, Stadt",
  "Gräfendorf",
  "Grafengehaig, Markt",
  "Grafenrheinfeld",
  "Grafenwiesen",
  "Grafenwöhr, Stadt",
  "Grafing b.München, Stadt",
  "Grafling",
  "Grafrath",
  "Grainau",
  "Grainet",
  "Grasbrunn",
  "Grassau, Markt",
  "Grattersdorf",
  "Greding, Stadt",
  "Greifenberg",
  "Greiling",
  "Gremsdorf",
  "Grettstadt",
  "Greußenheim",
  "Griesstätt",
  "Gröbenzell",
  "Großaitingen",
  "Großbardorf",
  "Großeibstadt",
  "Großenseebach",
  "Großhabersdorf",
  "Großheirath",
  "Großheubach, Markt",
  "Großkarolinenfeld",
  "Großlangheim, Markt",
  "Großmehring",
  "Großostheim, Markt",
  "Großwallstadt",
  "Großweil",
  "Grub a.Forst",
  "Grünenbach",
  "Grünwald",
  "Gstadt a.Chiemsee",
  "Gundelfingen a.d.Donau, Stadt",
  "Gundelsheim",
  "Gundremmingen",
  "Güntersleben",
  "Günzach",
  "Günzburg, Große Kreisstadt",
  "Gunzenhausen, Stadt",
  "Guteneck",
  "Gutenstetten",
  "Guttenberg",
  "Haag",
  "Haag a.d.Amper",
  "Haag i.OB, Markt",
  "Haar",
  "Haarbach",
  "Habach",
  "Hafenlohr",
  "Hagelstadt",
  "Hagenbüchach",
  "Hahnbach, Markt",
  "Haibach",
  "Haibach",
  "Haidmühle",
  "Haimhausen",
  "Haiming",
  "Hainsfarth",
  "Halblech",
  "Haldenwang",
  "Haldenwang",
  "Halfing",
  "Hallbergmoos",
  "Hallerndorf",
  "Hallstadt, Stadt",
  "Halsbach",
  "Hammelburg, Stadt",
  "Happurg",
  "Harburg (Schwaben), Stadt",
  "Harsdorf",
  "Hartenstein",
  "Haselbach",
  "Hasloch",
  "Haßfurt, Stadt",
  "Hattenhofen",
  "Haundorf",
  "Haunsheim",
  "Hausen",
  "Hausen",
  "Hausen",
  "Hausen",
  "Hausen b.Würzburg",
  "Hausham",
  "Hauzenberg, Stadt",
  "Hawangen",
  "Hebertsfelden",
  "Hebertshausen",
  "Heideck, Stadt",
  "Heidenheim, Markt",
  "Heigenbrücken",
  "Heiligenstadt i.OFr., Markt",
  "Heilsbronn, Stadt",
  "Heimbuchenthal",
  "Heimenkirch, Markt",
  "Heimertingen",
  "Heinersreuth",
  "Heinrichsthal",
  "Heldenstein",
  "Helmbrechts, Stadt",
  "Helmstadt, Markt",
  "Hemau, Stadt",
  "Hemhofen",
  "Hemmersheim",
  "Hendungen",
  "Henfenfeld",
  "Hengersberg, Markt",
  "Hepberg",
  "Herbstadt",
  "Heretsried",
  "Hergatz",
  "Hergensweiler",
  "Heroldsbach",
  "Heroldsberg, Markt",
  "Herrieden, Stadt",
  "Herrngiersdorf",
  "Herrsching a.Ammersee",
  "Hersbruck, Stadt",
  "Herzogenaurach, Stadt",
  "Heßdorf",
  "Hettenshausen",
  "Hettstadt",
  "Hetzles",
  "Heustreu",
  "Hilgertshausen-Tandern",
  "Hilpoltstein, Stadt",
  "Hiltenfingen",
  "Hiltpoltstein, Markt",
  "Himmelkron",
  "Himmelstadt",
  "Hinterschmiding",
  "Hirschaid, Markt",
  "Hirschau, Stadt",
  "Hirschbach",
  "Hitzhofen",
  "Höchberg, Markt",
  "Höchheim",
  "Höchstadt a.d.Aisch, Stadt",
  "Höchstädt a.d.Donau, Stadt",
  "Hochstadt a.Main",
  "Höchstädt i.Fichtelgebirge",
  "Hof",
  "Hofheim i.UFr., Stadt",
  "Hofkirchen, Markt",
  "Hofstetten",
  "Hohenaltheim",
  "Hohenau",
  "Hohenberg a.d.Eger, Stadt",
  "Hohenbrunn",
  "Hohenburg, Markt",
  "Hohenfels, Markt",
  "Hohenfurch",
  "Hohenkammer",
  "Höhenkirchen-Siegertsbrunn",
  "Hohenlinden",
  "Hohenpeißenberg",
  "Hohenpolding",
  "Hohenroth",
  "Hohenthann",
  "Hohenwart, Markt",
  "Hohenwarth",
  "Hollenbach",
  "Hollfeld, Stadt",
  "Hollstadt",
  "Holzgünz",
  "Holzheim",
  "Holzheim",
  "Holzheim",
  "Holzheim a.Forst",
  "Holzkirchen",
  "Holzkirchen, Markt",
  "Hopferau",
  "Horgau",
  "Hörgertshausen",
  "Hösbach, Markt",
  "Höslwang",
  "Höttingen",
  "Huglfing",
  "Huisheim",
  "Hummeltal",
  "Hunderdorf",
  "Hunding",
  "Hurlach",
  "Hutthurm, Markt",
  "Ichenhausen, Stadt",
  "Icking",
  "Iffeldorf",
  "Igensdorf, Markt",
  "Iggensbach",
  "Igling",
  "Ihrlerstein",
  "Illertissen, Stadt",
  "Illesheim",
  "Illschwang",
  "Ilmmünster",
  "Immenreuth",
  "Immenstadt i.Allgäu, Stadt",
  "Inchenhofen, Markt",
  "Ingenried",
  "Ingolstadt",
  "Innernzell",
  "Inning a.Ammersee",
  "Inning a.Holz",
  "Insingen",
  "Inzell",
  "Iphofen, Stadt",
  "Ippesheim, Markt",
  "Ipsheim, Markt",
  "Irchenrieth",
  "Irlbach",
  "Irschenberg",
  "Irsee, Markt",
  "Isen, Markt",
  "Ismaning",
  "Issigau",
  "Itzgrund",
  "Jachenau",
  "Jandelsbrunn",
  "Jengen",
  "Jesenwang",
  "Jettenbach",
  "Jettingen-Scheppach, Markt",
  "Jetzendorf",
  "Johannesberg",
  "Johanniskirchen",
  "Julbach",
  "Kahl a.Main",
  "Kaisheim, Markt",
  "Kalchreuth",
  "Kallmünz, Markt",
  "Kaltental, Markt",
  "Kammeltal",
  "Kammerstein",
  "Kammlach",
  "Karbach, Markt",
  "Karlsfeld",
  "Karlshuld",
  "Karlskron",
  "Karlstadt, Stadt",
  "Karlstein a.Main",
  "Karsbach",
  "Kasendorf, Markt",
  "Kastl",
  "Kastl",
  "Kastl, Markt",
  "Kaufbeuren",
  "Kaufering, Markt",
  "Kelheim, Stadt",
  "Kellmünz a.d.Iller, Markt",
  "Kemmern",
  "Kemnath, Stadt",
  "Kempten (Allgäu)",
  "Kettershausen",
  "Kiefersfelden",
  "Kienberg",
  "Kinding, Markt",
  "Kinsau",
  "Kipfenberg, Markt",
  "Kirchanschöring",
  "Kirchberg",
  "Kirchberg i.Wald",
  "Kirchdorf",
  "Kirchdorf",
  "Kirchdorf a.d.Amper",
  "Kirchdorf a.Inn",
  "Kirchdorf i.Wald",
  "Kirchehrenbach",
  "Kirchendemenreuth",
  "Kirchenlamitz, Stadt",
  "Kirchenpingarten",
  "Kirchensittenbach",
  "Kirchenthumbach, Markt",
  "Kirchham",
  "Kirchhaslach",
  "Kirchheim",
  "Kirchheim b.München",
  "Kirchheim i.Schw., Markt",
  "Kirchlauter",
  "Kirchroth",
  "Kirchseeon, Markt",
  "Kirchweidach",
  "Kirchzell, Markt",
  "Kissing",
  "Kist",
  "Kitzingen, Große Kreisstadt",
  "Kleinaitingen",
  "Kleinheubach, Markt",
  "Kleinkahl",
  "Kleinlangheim, Markt",
  "Kleinostheim",
  "Kleinrinderfeld",
  "Kleinsendelbach",
  "Kleinwallstadt, Markt",
  "Klingenberg a.Main, Stadt",
  "Klosterlechfeld",
  "Knetzgau",
  "Kochel a.See",
  "Köditz",
  "Ködnitz",
  "Köfering",
  "Kohlberg, Markt",
  "Kolbermoor, Stadt",
  "Kolitzheim",
  "Kollnburg",
  "Königsberg i.Bay., Stadt",
  "Königsbrunn, Stadt",
  "Königsdorf",
  "Königsfeld",
  "Königsmoos",
  "Königstein, Markt",
  "Konnersreuth, Markt",
  "Konradsreuth",
  "Konzell",
  "Kösching, Markt",
  "Kößlarn, Markt",
  "Kottgeisering",
  "Kötz",
  "Kraftisried",
  "Kraiburg a.Inn, Markt",
  "Krailling",
  "Kranzberg",
  "Kreuth",
  "Kreuzwertheim, Markt",
  "Krombach",
  "Kronach, Stadt",
  "Kronburg",
  "Kröning",
  "Krumbach (Schwaben), Stadt",
  "Krummennaab",
  "Krün",
  "Kühbach, Markt",
  "Kühlenthal",
  "Kulmain",
  "Kulmbach, Große Kreisstadt",
  "Kumhausen",
  "Kümmersbruck",
  "Kunreuth",
  "Künzing",
  "Kupferberg, Stadt",
  "Küps, Markt",
  "Kürnach",
  "Kutzenhausen",
  "Laaber, Markt",
  "Laberweinting",
  "Lachen",
  "Lalling",
  "Lam, Markt",
  "Lamerdingen",
  "Landau a.d.Isar, Stadt",
  "Landensberg",
  "Landsberg am Lech, Große Kreisstadt",
  "Landsberied",
  "Landshut",
  "Langdorf",
  "Langenaltheim",
  "Langenbach",
  "Langenfeld",
  "Langenmosen",
  "Langenneufnach",
  "Langenpreising",
  "Langensendelbach",
  "Langenzenn, Stadt",
  "Langerringen",
  "Langfurth",
  "Langquaid, Markt",
  "Langweid a.Lech",
  "Lappersdorf, Markt",
  "Lauben",
  "Lauben",
  "Laudenbach",
  "Lauf a.d.Pegnitz, Stadt",
  "Laufach",
  "Laufen, Stadt",
  "Laugna",
  "Lauingen (Donau), Stadt",
  "Lauter",
  "Lauterhofen, Markt",
  "Lautertal",
  "Lautrach",
  "Lechbruck am See",
  "Legau, Markt",
  "Lehrberg, Markt",
  "Leiblfing",
  "Leidersbach",
  "Leinach",
  "Leinburg",
  "Leipheim, Stadt",
  "Lengdorf",
  "Lengenwang",
  "Lenggries",
  "Lenting",
  "Leonberg",
  "Leuchtenberg, Markt",
  "Leupoldsgrün",
  "Leutenbach",
  "Leutershausen, Stadt",
  "Lichtenau, Markt",
  "Lichtenberg, Stadt",
  "Lichtenfels, Stadt",
  "Lindau (Bodensee), Große Kreisstadt",
  "Lindberg",
  "Lindenberg i.Allgäu, Stadt",
  "Lisberg",
  "Litzendorf",
  "Lohberg",
  "Lohkirchen",
  "Lohr a.Main, Stadt",
  "Loiching",
  "Loitzendorf",
  "Lonnerstadt, Markt",
  "Ludwigschorgast, Markt",
  "Ludwigsstadt, Stadt",
  "Luhe-Wildenau, Markt",
  "Lülsfeld",
  "Lupburg, Markt",
  "Lutzingen",
  "Mähring, Markt",
  "Maierhöfen",
  "Maihingen",
  "Mainaschaff",
  "Mainbernheim, Stadt",
  "Mainburg, Stadt",
  "Mainleus, Markt",
  "Mainstockheim",
  "Maisach",
  "Maitenbeth",
  "Malching",
  "Malgersdorf",
  "Mallersdorf-Pfaffenberg, Markt",
  "Mammendorf",
  "Mamming",
  "Manching, Markt",
  "Mantel, Markt",
  "Margetshöchheim",
  "Mariaposching",
  "Marklkofen",
  "Markt Berolzheim, Markt",
  "Markt Bibart, Markt",
  "Markt Einersheim, Markt",
  "Markt Erlbach, Markt",
  "Markt Indersdorf, Markt",
  "Markt Nordheim, Markt",
  "Markt Rettenbach, Markt",
  "Markt Schwaben, Markt",
  "Markt Taschendorf, Markt",
  "Markt Wald, Markt",
  "Marktbergel, Markt",
  "Marktbreit, Stadt",
  "Marktgraitz, Markt",
  "Marktheidenfeld, Stadt",
  "Marktl, Markt",
  "Marktleugast, Markt",
  "Marktleuthen, Stadt",
  "Marktoberdorf, Stadt",
  "Marktoffingen",
  "Marktredwitz, Große Kreisstadt",
  "Marktrodach, Markt",
  "Marktschellenberg, Markt",
  "Marktschorgast, Markt",
  "Marktsteft, Stadt",
  "Marktzeuln, Markt",
  "Marloffstein",
  "Maroldsweisach, Markt",
  "Marquartstein",
  "Martinsheim",
  "Marxheim",
  "Marzling",
  "Maßbach, Markt",
  "Massing, Markt",
  "Mauern",
  "Mauerstetten",
  "Mauth",
  "Maxhütte-Haidhof, Stadt",
  "Medlingen",
  "Meeder",
  "Megesheim",
  "Mehlmeisel",
  "Mehring",
  "Meinheim",
  "Meitingen, Markt",
  "Mellrichstadt, Stadt",
  "Memmelsdorf",
  "Memmingen",
  "Memmingerberg",
  "Mengkofen",
  "Merching",
  "Mering, Markt",
  "Merkendorf, Stadt",
  "Mertingen",
  "Mespelbrunn",
  "Metten, Markt",
  "Mettenheim",
  "Michelau i.OFr.",
  "Michelau i.Steigerwald",
  "Michelsneukirchen",
  "Mickhausen",
  "Miesbach, Stadt",
  "Miltach",
  "Miltenberg, Stadt",
  "Mindelheim, Stadt",
  "Mindelstetten",
  "Mintraching",
  "Missen-Wilhams",
  "Mistelbach",
  "Mistelgau",
  "Mitteleschenbach",
  "Mittelneufnach",
  "Mittelsinn",
  "Mittelstetten",
  "Mittenwald, Markt",
  "Mitterfels, Markt",
  "Mitterskirchen",
  "Mitterteich, Stadt",
  "Mitwitz, Markt",
  "Mödingen",
  "Möhrendorf",
  "Mömbris, Markt",
  "Mömlingen",
  "Mönchberg, Markt",
  "Mönchsdeggingen",
  "Mönchsroth",
  "Monheim, Stadt",
  "Moorenweis",
  "Moos",
  "Moosach",
  "Moosbach, Markt",
  "Moosburg a.d.Isar, Stadt",
  "Moosinning",
  "Moosthenning",
  "Mörnsheim, Markt",
  "Motten",
  "Möttingen",
  "Mötzing",
  "Mühldorf a.Inn, Stadt",
  "Mühlhausen",
  "Mühlhausen, Markt",
  "Muhr a.See",
  "Münchberg, Stadt",
  "München, Landeshauptstadt",
  "Münchsmünster",
  "Münchsteinach",
  "Münnerstadt, Stadt",
  "Munningen",
  "Münsing",
  "Münster",
  "Münsterhausen, Markt",
  "Murnau a.Staffelsee, Markt",
  "Nabburg, Stadt",
  "Nagel",
  "Naila, Stadt",
  "Nandlstadt, Markt",
  "Nassenfels, Markt",
  "Nennslingen, Markt",
  "Nersingen",
  "Nesselwang, Markt",
  "Neualbenreuth, Markt",
  "Neubeuern, Markt",
  "Neubiberg",
  "Neubrunn, Markt",
  "Neuburg a.d.Donau, Große Kreisstadt",
  "Neuburg a.d.Kammel, Markt",
  "Neuburg a.Inn",
  "Neuching",
  "Neudrossenfeld",
  "Neuendettelsau",
  "Neuendorf",
  "Neuenmarkt",
  "Neufahrn b.Freising",
  "Neufahrn i.NB",
  "Neufraunhofen",
  "Neuhaus a.d.Pegnitz, Markt",
  "Neuhaus a.Inn",
  "Neuhof a.d.Zenn, Markt",
  "Neuhütten",
  "Neukirchen",
  "Neukirchen b.Hl.Blut, Markt",
  "Neukirchen b.Sulzbach-Rosenberg",
  "Neukirchen vorm Wald",
  "Neukirchen-Balbini, Markt",
  "Neumarkt i.d.OPf., Große Kreisstadt",
  "Neumarkt-Sankt Veit, Stadt",
  "Neunburg vorm Wald, Stadt",
  "Neunkirchen",
  "Neunkirchen a.Brand, Markt",
  "Neunkirchen a.Sand",
  "Neuötting, Stadt",
  "Neureichenau",
  "Neuried",
  "Neusäß, Stadt",
  "Neuschönau",
  "Neusitz",
  "Neusorg",
  "Neustadt a.d.Aisch, Stadt",
  "Neustadt a.d.Donau, Stadt",
  "Neustadt a.d.Waldnaab, Stadt",
  "Neustadt a.Main",
  "Neustadt am Kulm, Stadt",
  "Neustadt b.Coburg, Große Kreisstadt",
  "Neutraubling, Stadt",
  "Neu-Ulm, Große Kreisstadt",
  "Niederaichbach",
  "Niederalteich",
  "Niederbergkirchen",
  "Niederfüllbach",
  "Niederlauer",
  "Niedermurach",
  "Niedernberg",
  "Niederrieden",
  "Niederschönenfeld",
  "Niedertaufkirchen",
  "Niederviehbach",
  "Niederwerrn",
  "Niederwinkling",
  "Nittenau, Stadt",
  "Nittendorf, Markt",
  "Nonnenhorn",
  "Nordendorf",
  "Nordhalben, Markt",
  "Nordheim a.Main",
  "Nordheim v.d.Rhön",
  "Nördlingen, Große Kreisstadt",
  "Nüdlingen",
  "Nürnberg",
  "Nußdorf",
  "Nußdorf a.Inn",
  "Oberammergau",
  "Oberasbach, Stadt",
  "Oberau",
  "Oberaudorf",
  "Oberaurach",
  "Oberbergkirchen",
  "Oberdachstetten",
  "Oberding",
  "Oberdolling",
  "Oberelsbach, Markt",
  "Obergriesbach",
  "Obergünzburg, Markt",
  "Oberhaching",
  "Oberhaid",
  "Oberhausen",
  "Oberhausen",
  "Oberickelsheim",
  "Oberkotzau, Markt",
  "Oberleichtersbach",
  "Obermaiselstein",
  "Obermeitingen",
  "Obermichelbach",
  "Obernbreit, Markt",
  "Obernburg a.Main, Stadt",
  "Oberndorf a.Lech",
  "Oberneukirchen",
  "Obernzell, Markt",
  "Obernzenn, Markt",
  "Oberostendorf",
  "Oberottmarshausen",
  "Oberpframmern",
  "Oberpleichfeld",
  "Oberpöring",
  "Oberreichenbach",
  "Oberreute",
  "Oberrieden",
  "Oberroth",
  "Oberscheinfeld, Markt",
  "Oberschleißheim",
  "Oberschneiding",
  "Oberschönegg",
  "Oberschwarzach, Markt",
  "Oberschweinbach",
  "Obersinn, Markt",
  "Obersöchering",
  "Oberstaufen, Markt",
  "Oberstdorf, Markt",
  "Oberstreu",
  "Obersüßbach",
  "Obertaufkirchen",
  "Oberthulba, Markt",
  "Obertraubling",
  "Obertrubach",
  "Oberviechtach, Stadt",
  "Obing",
  "Ochsenfurt, Stadt",
  "Odelzhausen",
  "Oerlenbach",
  "Oettingen i.Bay., Stadt",
  "Offenberg",
  "Offenhausen",
  "Offingen, Markt",
  "Ofterschwang",
  "Ohlstadt",
  "Ohrenbach",
  "Olching, Stadt",
  "Opfenbach",
  "Ornbau, Stadt",
  "Ortenburg, Markt",
  "Osterberg",
  "Osterhofen, Stadt",
  "Osterzell",
  "Ostheim v.d.Rhön, Stadt",
  "Ottenhofen",
  "Ottensoos",
  "Otterfing",
  "Otting",
  "Ottobeuren, Markt",
  "Ottobrunn",
  "Otzing",
  "Oy-Mittelberg",
  "Pähl",
  "Painten, Markt",
  "Palling",
  "Pappenheim, Stadt",
  "Parkstein, Markt",
  "Parkstetten",
  "Parsberg, Stadt",
  "Partenstein",
  "Passau",
  "Pastetten",
  "Patersdorf",
  "Paunzhausen",
  "Pechbrunn",
  "Pegnitz, Stadt",
  "Peißenberg, Markt",
  "Peiting, Markt",
  "Pemfling",
  "Pentling",
  "Penzberg, Stadt",
  "Penzing",
  "Perach",
  "Perasdorf",
  "Perkam",
  "Perlesreut, Markt",
  "Petersaurach",
  "Petersdorf",
  "Petershausen",
  "Pettendorf",
  "Petting",
  "Pettstadt",
  "Pfaffenhausen, Markt",
  "Pfaffenhofen a.d.Glonn",
  "Pfaffenhofen a.d.Ilm, Stadt",
  "Pfaffenhofen a.d.Roth, Markt",
  "Pfaffing",
  "Pfakofen",
  "Pfarrkirchen, Stadt",
  "Pfarrweisach",
  "Pfatter",
  "Pfeffenhausen, Markt",
  "Pfofeld",
  "Pförring, Markt",
  "Pforzen",
  "Pfreimd, Stadt",
  "Pfronten",
  "Philippsreut",
  "Piding",
  "Pielenhofen",
  "Pilsach",
  "Pilsting, Markt",
  "Pinzberg",
  "Pirk",
  "Pittenhart",
  "Planegg",
  "Plankenfels",
  "Plattling, Stadt",
  "Plech, Markt",
  "Pleinfeld, Markt",
  "Pleiskirchen",
  "Pleß",
  "Pleystein, Stadt",
  "Pliening",
  "Plößberg, Markt",
  "Pöcking",
  "Pocking, Stadt",
  "Poing",
  "Pollenfeld",
  "Polling",
  "Polling",
  "Polsingen",
  "Pommelsbrunn",
  "Pommersfelden",
  "Poppenhausen",
  "Poppenricht",
  "Pörnbach",
  "Pösing",
  "Postau",
  "Postbauer-Heng, Markt",
  "Postmünster",
  "Pottenstein, Stadt",
  "Pöttmes, Markt",
  "Poxdorf",
  "Prackenbach",
  "Prebitz",
  "Prem",
  "Pressath, Stadt",
  "Presseck, Markt",
  "Pressig, Markt",
  "Pretzfeld, Markt",
  "Prichsenstadt, Stadt",
  "Prien a.Chiemsee, Markt",
  "Priesendorf",
  "Prittriching",
  "Prosselsheim",
  "Prutting",
  "Püchersreuth",
  "Puchheim, Stadt",
  "Pullach i.Isartal",
  "Pullenreuth",
  "Pürgen",
  "Puschendorf",
  "Putzbrunn",
  "Pyrbaum, Markt",
  "Rain",
  "Rain, Stadt",
  "Raisting",
  "Raitenbuch",
  "Ramerberg",
  "Rammingen",
  "Ramsau b.Berchtesgaden",
  "Ramsthal",
  "Randersacker, Markt",
  "Rannungen",
  "Rattelsdorf, Markt",
  "Rattenberg",
  "Rattenkirchen",
  "Rattiszell",
  "Raubling",
  "Rauhenebrach",
  "Rechtenbach",
  "Rechtmehring",
  "Reckendorf",
  "Rednitzhembach",
  "Redwitz a.d.Rodach",
  "Regen, Stadt",
  "Regensburg",
  "Regenstauf, Markt",
  "Regnitzlosau",
  "Rehau, Stadt",
  "Rehling",
  "Reichenbach",
  "Reichenbach",
  "Reichenberg, Markt",
  "Reichenschwand",
  "Reichersbeuern",
  "Reichertshausen",
  "Reichertsheim",
  "Reichertshofen, Markt",
  "Reichling",
  "Reimlingen",
  "Reisbach, Markt",
  "Reischach",
  "Reit im Winkl",
  "Remlingen, Markt",
  "Rennertshofen, Markt",
  "Rentweinsdorf, Markt",
  "Rettenbach",
  "Rettenbach",
  "Rettenbach a.Auerberg",
  "Rettenberg",
  "Retzstadt",
  "Reut",
  "Reuth b.Erbendorf",
  "Ried",
  "Riedbach",
  "Rieden",
  "Rieden am Forggensee",
  "Rieden, Markt",
  "Riedenberg",
  "Riedenburg, Stadt",
  "Riedenheim",
  "Riedering",
  "Riegsee",
  "Riekofen",
  "Rieneck, Stadt",
  "Rimbach",
  "Rimbach",
  "Rimpar, Markt",
  "Rimsting",
  "Rinchnach",
  "Ringelai",
  "Röckingen",
  "Rödelmaier",
  "Rödelsee",
  "Roden",
  "Rödental, Stadt",
  "Roding, Stadt",
  "Röfingen",
  "Roggenburg",
  "Rögling",
  "Rohr",
  "Rohr i.NB, Markt",
  "Rohrbach",
  "Rohrdorf",
  "Rohrenfels",
  "Röhrmoos",
  "Röhrnbach, Markt",
  "Röllbach",
  "Ronsberg, Markt",
  "Rosenheim",
  "Röslau",
  "Roßbach",
  "Roßhaupten",
  "Roßtal, Markt",
  "Roth, Stadt",
  "Röthenbach (Allgäu)",
  "Röthenbach a.d.Pegnitz, Stadt",
  "Rothenbuch",
  "Rothenburg ob der Tauber, Große Kreisstadt",
  "Rothenfels, Stadt",
  "Röthlein",
  "Rott",
  "Rott a.Inn",
  "Rottach-Egern",
  "Röttenbach",
  "Röttenbach",
  "Rottenbuch",
  "Rottenburg a.d.Laaber, Stadt",
  "Rottendorf",
  "Rotthalmünster, Markt",
  "Röttingen, Stadt",
  "Rötz, Stadt",
  "Rückersdorf",
  "Rückholz",
  "Rudelzhausen",
  "Rüdenau",
  "Rüdenhausen, Markt",
  "Ruderatshofen",
  "Ruderting",
  "Rugendorf",
  "Rügland",
  "Ruhmannsfelden, Markt",
  "Ruhpolding",
  "Ruhstorf a.d.Rott, Markt",
  "Runding",
  "Saal a.d.Donau",
  "Saal a.d.Saale, Markt",
  "Saaldorf-Surheim",
  "Sachsen b.Ansbach",
  "Sachsenkam",
  "Sailauf",
  "Salching",
  "Saldenburg",
  "Salgen",
  "Salz",
  "Salzweg",
  "Samerberg",
  "Sand a.Main",
  "Sandberg",
  "Sankt Englmar",
  "Sankt Oswald-Riedlhütte",
  "Sankt Wolfgang",
  "Sauerlach",
  "Saulgrub",
  "Schäftlarn",
  "Schalkham",
  "Schauenstein, Stadt",
  "Schaufling",
  "Schechen",
  "Scheidegg, Markt",
  "Scheinfeld, Stadt",
  "Schernfeld",
  "Scherstetten",
  "Scheßlitz, Stadt",
  "Scheuring",
  "Scheyern",
  "Schierling, Markt",
  "Schillingsfürst, Stadt",
  "Schiltberg",
  "Schirmitz",
  "Schirnding, Markt",
  "Schlammersdorf",
  "Schleching",
  "Schlehdorf",
  "Schliersee, Markt",
  "Schlüsselfeld, Stadt",
  "Schmidgaden",
  "Schmidmühlen, Markt",
  "Schmiechen",
  "Schnabelwaid, Markt",
  "Schnaitsee",
  "Schnaittach, Markt",
  "Schnaittenbach, Stadt",
  "Schneckenlohe",
  "Schneeberg, Markt",
  "Schneizlreuth",
  "Schnelldorf",
  "Schöfweg",
  "Schollbrunn",
  "Schöllkrippen, Markt",
  "Schöllnach, Markt",
  "Schönau",
  "Schönau a.d.Brend",
  "Schönau a.Königssee",
  "Schönberg",
  "Schönberg, Markt",
  "Schönbrunn i.Steigerwald",
  "Schondorf am Ammersee",
  "Schondra, Markt",
  "Schongau, Stadt",
  "Schöngeising",
  "Schönsee, Stadt",
  "Schonstett",
  "Schönthal",
  "Schonungen",
  "Schönwald, Stadt",
  "Schopfloch, Markt",
  "Schorndorf",
  "Schrobenhausen, Stadt",
  "Schwabach",
  "Schwabbruck",
  "Schwabhausen",
  "Schwabmünchen, Stadt",
  "Schwabsoien",
  "Schwaig b.Nürnberg",
  "Schwaigen",
  "Schwandorf, Große Kreisstadt",
  "Schwanfeld",
  "Schwangau",
  "Schwanstetten, Markt",
  "Schwarzach a.Main, Markt",
  "Schwarzach b.Nabburg",
  "Schwarzach, Markt",
  "Schwarzenbach",
  "Schwarzenbach a.d.Saale, Stadt",
  "Schwarzenbach a.Wald, Stadt",
  "Schwarzenbruck",
  "Schwarzenfeld, Markt",
  "Schwarzhofen, Markt",
  "Schwebheim",
  "Schweinfurt",
  "Schweitenkirchen",
  "Schwenningen",
  "Schwifting",
  "Schwindegg",
  "Seefeld",
  "Seeg",
  "Seehausen a.Staffelsee",
  "Seeon-Seebruck",
  "Seeshaupt",
  "Segnitz",
  "Seinsheim, Markt",
  "Selb, Große Kreisstadt",
  "Selbitz, Stadt",
  "Senden, Stadt",
  "Sengenthal",
  "Sennfeld",
  "Seßlach, Stadt",
  "Seubersdorf i.d.OPf.",
  "Seukendorf",
  "Seybothenreuth",
  "Siegenburg, Markt",
  "Siegsdorf",
  "Sielenbach",
  "Sigmarszell",
  "Simbach a.Inn, Stadt",
  "Simbach, Markt",
  "Simmelsdorf",
  "Simmershofen",
  "Sindelsdorf",
  "Sinzing",
  "Söchtenau",
  "Solnhofen",
  "Sommerach",
  "Sommerhausen, Markt",
  "Sommerkahl",
  "Sonderhofen",
  "Sondheim v.d.Rhön",
  "Sonnefeld",
  "Sonnen",
  "Sontheim",
  "Sonthofen, Stadt",
  "Soyen",
  "Spalt, Stadt",
  "Spardorf",
  "Sparneck, Markt",
  "Spatzenhausen",
  "Speichersdorf",
  "Speinshart",
  "Spiegelau",
  "Stadelhofen",
  "Stadlern",
  "Stadtbergen, Stadt",
  "Stadtlauringen, Markt",
  "Stadtprozelten, Stadt",
  "Stadtsteinach, Stadt",
  "Stallwang",
  "Stammbach, Markt",
  "Stammham",
  "Stammham",
  "Stamsried, Markt",
  "Starnberg, Stadt",
  "Staudach-Egerndach",
  "Stegaurach",
  "Stein, Stadt",
  "Steinach",
  "Steinbach a.Wald",
  "Steinberg am See",
  "Steindorf",
  "Steinfeld",
  "Steingaden",
  "Steinhöring",
  "Steinkirchen",
  "Steinsfeld",
  "Steinwiesen, Markt",
  "Stephanskirchen",
  "Stephansposching",
  "Stetten",
  "Stettfeld",
  "Stiefenhofen",
  "Stockheim",
  "Stockheim",
  "Stockstadt a.Main, Markt",
  "Störnstein",
  "Stötten a.Auerberg",
  "Stöttwang",
  "Strahlungen",
  "Straßkirchen",
  "Straßlach-Dingharting",
  "Straubing",
  "Strullendorf",
  "Stubenberg",
  "Stulln",
  "Sugenheim, Markt",
  "Sulzbach a.Main, Markt",
  "Sulzbach-Rosenberg, Stadt",
  "Sulzberg, Markt",
  "Sulzdorf a.d.Lederhecke",
  "Sulzemoos",
  "Sulzfeld",
  "Sulzfeld a.Main",
  "Sulzheim",
  "Sulzthal, Markt",
  "Sünching",
  "Surberg",
  "Syrgenstein",
  "Tacherting",
  "Taching a.See",
  "Tagmersheim",
  "Tann, Markt",
  "Tännesberg, Markt",
  "Tapfheim",
  "Tauberrettersheim",
  "Taufkirchen",
  "Taufkirchen",
  "Taufkirchen (Vils)",
  "Tegernheim",
  "Tegernsee, Stadt",
  "Teisendorf, Markt",
  "Teising",
  "Teisnach, Markt",
  "Tettau, Markt",
  "Tettenweis",
  "Teublitz, Stadt",
  "Teugn",
  "Teunz",
  "Teuschnitz, Stadt",
  "Thaining",
  "Thalmassing",
  "Thalmässing, Markt",
  "Thannhausen, Stadt",
  "Thanstein",
  "Theilenhofen",
  "Theilheim",
  "Theisseil",
  "Theres",
  "Thierhaupten, Markt",
  "Thiersheim, Markt",
  "Thierstein, Markt",
  "Thundorf i.UFr.",
  "Thüngen, Markt",
  "Thüngersheim",
  "Thurmansbang",
  "Thurnau, Markt",
  "Thyrnau",
  "Tiefenbach",
  "Tiefenbach",
  "Tiefenbach",
  "Tirschenreuth, Stadt",
  "Titting, Markt",
  "Tittling, Markt",
  "Tittmoning, Stadt",
  "Todtenweis",
  "Töging a.Inn, Stadt",
  "Töpen",
  "Trabitz",
  "Train",
  "Traitsching",
  "Trappstadt, Markt",
  "Traunreut, Stadt",
  "Traunstein, Große Kreisstadt",
  "Trausnitz",
  "Trautskirchen",
  "Trebgast",
  "Treffelstein",
  "Treuchtlingen, Stadt",
  "Triefenstein, Markt",
  "Triftern, Markt",
  "Trogen",
  "Tröstau",
  "Trostberg, Stadt",
  "Trunkelsberg",
  "Tschirn",
  "Tuchenbach",
  "Tuntenhausen",
  "Türkenfeld",
  "Türkheim, Markt",
  "Tussenhausen, Markt",
  "Tüßling, Markt",
  "Tutzing",
  "Tyrlaching",
  "Übersee",
  "Üchtelhausen",
  "Uehlfeld, Markt",
  "Uettingen",
  "Uffenheim, Stadt",
  "Uffing a.Staffelsee",
  "Ungerhausen",
  "Unsleben",
  "Unterammergau",
  "Unterdießen",
  "Unterdietfurt",
  "Unteregg",
  "Unterföhring",
  "Untergriesbach, Markt",
  "Unterhaching",
  "Unterleinleiter",
  "Untermeitingen",
  "Untermerzbach",
  "Unterneukirchen",
  "Unterpleichfeld",
  "Unterreit",
  "Unterroth",
  "Unterschleißheim, Stadt",
  "Unterschwaningen",
  "Untersiemau",
  "Untersteinach",
  "Unterthingau, Markt",
  "Unterwössen",
  "Untrasried",
  "Ursberg",
  "Ursensollen",
  "Urspringen",
  "Ustersbach",
  "Uttenreuth",
  "Utting am Ammersee",
  "Vachendorf",
  "Valley",
  "Vaterstetten",
  "Veitsbronn",
  "Veitshöchheim",
  "Velburg, Stadt",
  "Velden, Markt",
  "Velden, Stadt",
  "Vestenbergsgreuth, Markt",
  "Viechtach, Stadt",
  "Viereth-Trunstadt",
  "Vierkirchen",
  "Vilgertshofen",
  "Villenbach",
  "Vilsbiburg, Stadt",
  "Vilseck, Stadt",
  "Vilsheim",
  "Vilshofen an der Donau, Stadt",
  "Vogtareuth",
  "Vohburg a.d.Donau, Stadt",
  "Vohenstrauß, Stadt",
  "Vöhringen, Stadt",
  "Volkach, Stadt",
  "Volkenschwand",
  "Vorbach",
  "Vorra",
  "Waakirchen",
  "Waal, Markt",
  "Wachenroth, Markt",
  "Wackersberg",
  "Wackersdorf",
  "Waffenbrunn",
  "Waging a.See, Markt",
  "Waidhaus, Markt",
  "Waidhofen",
  "Waigolshausen",
  "Waischenfeld, Stadt",
  "Wald",
  "Wald",
  "Waldaschaff",
  "Waldbrunn",
  "Waldbüttelbrunn",
  "Walderbach",
  "Waldershof, Stadt",
  "Waldkirchen, Stadt",
  "Waldkraiburg, Stadt",
  "Waldmünchen, Stadt",
  "Waldsassen, Stadt",
  "Waldstetten, Markt",
  "Waldthurn, Markt",
  "Walkertshofen",
  "Wallenfels, Stadt",
  "Wallerfing",
  "Wallersdorf, Markt",
  "Wallerstein, Markt",
  "Wallgau",
  "Walpertskirchen",
  "Walsdorf",
  "Waltenhausen",
  "Waltenhofen",
  "Walting",
  "Wang",
  "Warmensteinach",
  "Warngau",
  "Wartenberg, Markt",
  "Wartmannsroth",
  "Wasserburg (Bodensee)",
  "Wasserburg a.Inn, Stadt",
  "Wasserlosen",
  "Wassertrüdingen, Stadt",
  "Wattendorf",
  "Wechingen",
  "Wegscheid, Markt",
  "Wehringen",
  "Weibersbrunn",
  "Weichering",
  "Weichs",
  "Weiden i.d.OPf.",
  "Weidenbach, Markt",
  "Weidenberg, Markt",
  "Weidhausen b.Coburg",
  "Weiding",
  "Weiding",
  "Weigendorf",
  "Weigenheim",
  "Weihenzell",
  "Weiherhammer",
  "Weihmichl",
  "Weil",
  "Weilbach, Markt",
  "Weilersbach",
  "Weiler-Simmerberg, Markt",
  "Weilheim i.OB, Stadt",
  "Weiltingen, Markt",
  "Weisendorf, Markt",
  "Weismain, Stadt",
  "Weißdorf",
  "Weißenbrunn",
  "Weißenburg i.Bay., Große Kreisstadt",
  "Weißenhorn, Stadt",
  "Weißenohe",
  "Weißensberg",
  "Weißenstadt, Stadt",
  "Weitnau, Markt",
  "Weitramsdorf",
  "Welden, Markt",
  "Wellheim, Markt",
  "Wemding, Stadt",
  "Wendelstein, Markt",
  "Weng",
  "Wenzenbach",
  "Wernberg-Köblitz, Markt",
  "Werneck, Markt",
  "Wertach, Markt",
  "Wertingen, Stadt",
  "Weßling",
  "Wessobrunn",
  "Westendorf",
  "Westendorf",
  "Westerheim",
  "Westerngrund",
  "Westheim",
  "Wettringen",
  "Wettstetten",
  "Weyarn",
  "Wiedergeltingen",
  "Wielenbach",
  "Wiesau, Markt",
  "Wiesen",
  "Wiesenbach",
  "Wiesenbronn",
  "Wiesenfelden",
  "Wiesent",
  "Wiesenthau",
  "Wiesentheid, Markt",
  "Wiesenttal, Markt",
  "Wieseth",
  "Wiesthal",
  "Wiggensbach, Markt",
  "Wilburgstetten",
  "Wildenberg",
  "Wildflecken, Markt",
  "Wildpoldsried",
  "Wildsteig",
  "Wilhelmsdorf",
  "Wilhelmsthal",
  "Wilhermsdorf, Markt",
  "Willanzheim, Markt",
  "Willmars",
  "Willmering",
  "Windach",
  "Windberg",
  "Windelsbach",
  "Windischeschenbach, Stadt",
  "Windorf, Markt",
  "Windsbach, Stadt",
  "Winhöring",
  "Winkelhaid",
  "Winklarn, Markt",
  "Winterbach",
  "Winterhausen, Markt",
  "Winterrieden",
  "Winzer, Markt",
  "Wipfeld",
  "Wirsberg, Markt",
  "Wittelshofen",
  "Wittibreut",
  "Wittislingen, Markt",
  "Witzmannsberg",
  "Wolfersdorf",
  "Wolferstadt",
  "Wolfertschwenden",
  "Wolframs-Eschenbach, Stadt",
  "Wolfratshausen, Stadt",
  "Wolfsegg",
  "Wollbach",
  "Wolnzach, Markt",
  "Wonfurt",
  "Wonneberg",
  "Wonsees, Markt",
  "Woringen",
  "Wörnitz",
  "Wörth",
  "Wörth a.d.Donau, Stadt",
  "Wörth a.d.Isar",
  "Wörth a.Main, Stadt",
  "Wörthsee",
  "Wülfershausen a.d.Saale",
  "Wunsiedel, Stadt",
  "Wurmannsquick, Markt",
  "Wurmsham",
  "Würzburg",
  "Zachenberg",
  "Zandt",
  "Zangberg",
  "Zapfendorf, Markt",
  "Zeil a.Main, Stadt",
  "Zeilarn",
  "Zeitlarn",
  "Zeitlofs, Markt",
  "Zell",
  "Zell a.Main, Markt",
  "Zell im Fichtelgebirge, Markt",
  "Zellingen, Markt",
  "Zenting",
  "Ziemetshausen, Markt",
  "Ziertheim",
  "Zirndorf, Stadt",
  "Zolling",
  "Zorneding",
  "Zöschingen",
  "Zusamaltheim",
  "Zusmarshausen, Markt",
  "Zwiesel, Stadt"
];

module.exports = SelektierbareOptionenAufzaehlungsWertGemeindenBY;
